run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: false
  build-tags:
    - mytag
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true
output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  path-prefix: ""
  sort-results: false
  show-stats: true

linters:
  disable-all: true
  enable:
    - whitespace
    - wsl
    - musttag
    - unused
    - gci
    - importas
    - tagliatelle

linters-settings:
  gci:
    custom-oder: true
    sections:
      - standard
      - default
      - blank
      - dot
      - localmodule
  importas:
    no-extra-aliases: true
    alias:
      - pkg: "github.com/Agustincou/go-crud-api-example/internal/errors"
        alias: apierrors
  unused:
    field-writes-are-uses: false
    post-statements-are-reads: false
    exported-fields-are-used: false
    parameters-are-used: false
    local-variables-are-used: false
    generated-is-used: true
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: camel
        xml: camel
        mapstructure: kebab
        env: upperSnake
        envconfig: upperSnake

issues:
  exclude:
    - "var `_` is unused"
